[features]
seeds = false
skip-lint = false
[programs.localnet]
the_begin = "EUm7VJBMPkoExd8XLXKheKS8b7ktgdGPaUTs4CqyR7xu"

[programs.devnet]
the_begin = "EUm7VJBMPkoExd8XLXKheKS8b7ktgdGPaUTs4CqyR7xu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lucas/.config/solana/id.json"

[scripts]
# test = "yarn run mocha -t 1000000 tests/"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
